force-app/main/default/objects/Follow_Up__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Test Ride</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Needs More Time</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Information</fullName>
            </value>
            <value>
                <fullName>RNR</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
                <isActive>false</isActive>
                <label>Not Started</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Test_Drive__c/Test_Drive__c.object-meta.xml
<CustomObject>
    <label>Test Drive</label>
    <nameField>
        <label>Test Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Drives</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/MobileApp_DashboardTest.cls
@isTest(seeAllData=true)
public class MobileApp_DashboardTest {
    @isTest
    public Static void testLeadTotalLeads(){
        User usr = UtilityTestClass.createSalesManagerUser();
        System.runAs(usr) {
            Account testAccount = UtilityTestClass.createTestAccount('Test Account', 'C001', 'Test Store', '560076', 'Customer');
            Opportunity opp = UtilityTestClass.createTestOpportunity( 'Test Opportunity', testAccount.Id, 'RNR', System.today().addDays(30), 10000 );
            opp.OwnerId = usr.Id; update opp;
            
            Order ord = new Order(  Status = 'Activated',AccountId = testAccount.Id, OpportunityId = opp.Id, EffectiveDate = Date.today(), OwnerId = usr.Id );
            insert ord;
            
            Test_Drive__c td = UtilityTestClass.createTest1Driver('Test Drive Existing', opp.Id, 'Scheduled');
            td.OwnerId = usr.Id; td.Start_Date__c = DateTime.now(); update td;
            
            Follow_Up__c fu = UtilityTestClass.createFollowUp('Test Follow Up', null, opp.Id);
            fu.Status__c = 'New';fu.OwnerId= UserInfo.getUserId(); update fu;
            
            MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper wrp = new MobileApp_Wrapper.MobileApp_LeadTotalLeadsWrapper();
            wrp.UserId = usr.Id;
            wrp.FilterDate = '2026-08-15';
            wrp.FilterEndRange = '2026-09-16';
            String reqBody = JSON.serialize(wrp);
            
            RestRequest req = new RestRequest();
            req.requestBody = Blob.valueOf(reqBody);
            req.httpMethod = 'POST';
            req.requestURI = '/services/apexrest/userDashboard';
            RestContext.request = req;
            
            RestResponse res = new RestResponse();
            RestContext.response = res;
            
            MobileApp_Dashboard.LeadTotalLeads();

        }
    }
}